export const appConfig = {
  APP_TITLE: process.env.REACT_APP_NAME,
  APP_MODE: process.env.REACT_APP_MODE,
  API_URL: process.env.REACT_APP_API_URL,
  IMAGE_URL: process.env.REACT_APP_API_IMAGE_URL,
  ENCRYPTION_SECRET_KEY: process.env.REACT_APP_ENCRYPTION_SECRET_KEY,
  ENCRYPTION_MESSAGE: process.env.REACT_APP_ENCRYPTION_MESSAGE,
  DEVICE_TYPE: process.env.REACT_DEVICE_TYPE,
  STRIPE_PUBLIC_KEY: process.env.REACT_APP_STRIPE_PUBLIC_KEY,
  STRIPE_SECRET_KEY: process.env.REACT_APP_STRIPE_SECRET_KEY,
};
